version: "3.3"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo/petes-pets
      WAIT_HOSTS: mongo:27017

volumes:
  mongo_data: